CC=g++

all: MyBot first_bot second_bot third_bot seventh_bot accident_bot

clean:
	rm -rf *.o MyBot first_bot second_bot third_bot seventh_bot accident_bot

MyBot: MyBot.o PlanetWars.o

first_bot: first_bot.o PlanetWars.o

second_bot: second_bot.o PlanetWars.o

third_bot: third_bot.o PlanetWars.o

seventh_bot: seventh_bot.o PlanetWars.o

accident_bot: accident_bot.o PlanetWars.o
